routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::get('/','HomeController@index')->name('home.index');
// Route::group(['prefix'=>'drink'],function(){
//     Route::get('/','DrinkController@index');
// });

// Vue
Route::prefix('drink')->group(function(){
    Route::get('/','DrinkController@index')->name('drink.index');
    Route::post('/get_drinks','DrinkController@get_drinks');
});

// CRUD
Route::resource('blog','BlogController');


// Email
Route::prefix('email')->group(function(){
    Route::get('/','MailController@index')->name('email.index');
    Route::post('/normal','MailController@normal')->name('email.normal');
    Route::post('/cart','MailController@cart')->name('email.cart');
    Route::get('/cart','MailController@cart')->name('email.cart2');
});

Route::get('sendmail', function() {
 $data = ['name' => 'Test'];
 Mail::send('email.welcome', $data, function($message) {
  $message->to('myginnygo@gmail.com')->subject('This is test email');
 });
 return 'Your email has been sent successfully!';
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    //
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $blogs = Blog::orderBy('id','desc')->get();
        return view('blog.main',['blogs'=>$blogs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'title'=>'required|max:100',
            'subtitle'=>'required|max:100',
            'content'=>'required'
        ]);

        $blog = new Blog();

        if (Input::hasFile('blogimg')) {
            $file = Input::file('blogimg');
            $file->move('upload',$file->getClientOriginalName());
            $blog->blogimg = $file->getClientOriginalName();
        }

        $blog->title = $request->title;
        $blog->subtitle = $request->subtitle;
        $blog->content = $request->content;
        // $blog->created_at = time();
        $blog->save();
        
        return redirect()->route('blog.show',$blog->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //

        return view('blog.show',['blog'=>$blog]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        //
        return view('blog.edit',['blog'=>$blog]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        //
        $validate = $this->validate($request,[
            'title'=>'required|max:100',
            'subtitle'=>'required|max:100',
            'content'=>'required'
        ]);

        $model = Blog::find($blog->id);

        if (Input::hasFile('blogimg')) {
            $file = Input::file('blogimg');
            $file->move('upload',$file->getClientOriginalName());
            $model->blogimg = $file->getClientOriginalName();
        }

        $model->title = $request->title;
        $model->subtitle = $request->subtitle;
        $model->content = $request->content;
        $model->save();

        return redirect()->route('blog.show',$blog->id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $model = Blog::find($blog->id);
        $model->delete();
    }
}

resources/views/blog/create.blade.php
@extends('layouts.master')

@section('source')
<link rel="stylesheet" href="{{ URL::asset('css/blog/create.css') }}">
@endsection

@section('content')
    <div class="jumbotron">
        <div class="container">
            <h1>This is Create blade</h1>
            <h3>Which creates a new item</h3>
            <a href="{{ route('blog.index') }}" class="btn btn-primary"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
        </div>
    </div>
    <div class="container">
        <form action="{{ route('blog.store') }}" method="POST" class="create_form" enctype="multipart/form-data">
            <div class="form-group">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <label for="title">Title: </label>
                <input type="text" name="title" class="form-control">
                <label for="subtitle">Subtitle: </label>
                <input type="text" name="subtitle" class="form-control">
                <label for="blogimg">Image</label>
                <input type="file" name="blogimg">
                <label for="content">Content: </label>
                <textarea id="my-textarea" name="content" name="content" cols="30" rows="10" class="form-control"></textarea>
                <input type="submit" value="Create" class="btn btn-primary form-control">
            </div>
        </form>
    </div>
@endsection
        

@section('script')
<script>
    enableTab('my-textarea');
</script>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.master')

@section('source')
<link rel="stylesheet" href="{{ URL::asset('css/blog/show.css') }}">
@endsection

@section('content')
    <div class="jumbotron">
        <div class="container">
            <h1>This is Edit blade</h1>
            <h3>Which updates specific item</h3>
            <a href="{{ route('blog.index') }}" class="btn btn-primary"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 panel panel-default blog-area">
                <form action="{{ route('blog.update',$blog->id) }}" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <label for="title">Title: </label>
                        <input type="text" name="title" class="form-control" value="{{ $blog->title }}">
                        <label for="subtitle">Subtitle: </label>
                        <input type="text" name="subtitle" class="form-control" value="{{ $blog->subtitle }}">
                        <label for="blogimg">Image</label>
                        @if ($blog->blogimg)
                        <input id="edit-file" type="file" name="blogimg" value="{{ URL::asset('upload/'.$blog->blogimg) }}">
                        {{-- <img src="{{ URL::asset('upload/'.$blog->blogimg) }}" alt="" id="edit-img"> --}}
                        @else
                        <input id="edit-file" type="file" name="blogimg" value="">
                        {{-- <img src="" alt="" id="edit-img"> --}}
                        @endif
                        <label for="content">Content: </label>
                        <textarea id="my-textarea" name="content" cols="30" rows="10" class="form-control" >{{ $blog->content }}</textarea>
                        <input type="submit" value="Update" class="btn btn-success form-control">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script>
enableTab('my-textarea');
$("#edit-file").change(function(){
    $("#edit-img").attr('src',$("#edit-file").attr('value'));
});
</script>
@endsection

resources/views/blog/main.blade.php
@extends('layouts.master')

@section('source')
<link rel="stylesheet" href="css/blog/main.css">
@endsection

@section('content')
<div class="jumbotron">
    <div class="container">
        <h2>Classic example to show the usage of CRUD</h2>
        <h3>Create Read Update Destroy</h3>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-xs-12 sidebar_area">
            <div class="panel panel-default sidebar">
                <a href="{{ route('blog.create') }}" class="btn btn-primary form-control">Create new Blog</a>
            </div>
        </div>        

        <div class="col-sm-9 col-xs-10 col-sm-offset-0 col-xs-offset-1">
            @foreach ($blogs as $blog)
                <div class="row panel panel-default blogpanel">
                    <div class="col-md-4 col-sm-8 col-xs-12">
                        <h3>{{ $blog->title }}</h3>
                        <h5>{{ $blog->subtitle }}</h5>
                        <p>{!! nl2br(substr($blog->content,0,50)) !!}...</p>
                        <a class="btn btn-primary" href="{{ route('blog.show',[$blog->id]) }}">read more</a>
                        <br><br>
                    </div>
                    <div class="col-md-4 col-md-hidden col-xs-hidden">
                        @if ($blog->blogimg)
                        <img src="{{ URL::asset('upload/'.$blog->blogimg) }}" alt="" class="blogimg hidden-xs" >
                        @endif
                    </div>
                    <div class="col-sm-4 col-xs-12">
                        <div class="created_dt">{{ substr($blog->created_at,0,10) }}</div>
                        <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-success form-control margin-d5">Edit</a>
                        <button onclick="blog_destroy({{ $blog->id }})" class="btn btn-warning form-control" id="delblog">Destroy</button>
                    </div>
                </div>
            @endforeach
            
        </div>
    </div>
</div>
    
@endsection

@section('script')
<script>
function blog_destroy(id){
    if(confirm("Are you sure do delete this blog?")){
        $.ajax({
            url: "{{ url('/blog') }}/"+id,
            method: "DELETE",
            data: {
                _token: '{{ csrf_token() }}'
            },
            success: function(){
                location.reload();
            }
        });
    } else {
        return;
    }
}
</script>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.master')

@section('source')
<link rel="stylesheet" href="{{ URL::asset('css/blog/show.css') }}">
@endsection

@section('content')
    <div class="jumbotron">
        <div class="container">
            <h1>This is show blade</h1>
            <h3>Which shows specific item</h3>
            <a href="{{ route('blog.index') }}" class="btn btn-primary"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 panel panel-default blog-area">
                <h1>{{ $blog->title }}</h1>
                <h3>{{ $blog->subtitle }}</h2>
                <img src="{{ URL::asset('upload/'.$blog->blogimg) }}" class="showimg" alt="">
                <pre>{{ $blog->content }}</pre>
                <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-success form-control margin-d5">Edit</a>
                <button onclick="blog_destroy({{ $blog->id }})" class="btn btn-warning form-control margin-d5" id="delblog">Destroy</button>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script>
function blog_destroy(id){
    if(confirm("Are you sure do delete this blog?")){
        $.ajax({
            url: "{{ url('/blog') }}/"+id,
            method: "DELETE",
            data: {
                _token: '{{ csrf_token() }}'
            },
            success: function(){
                location.reload();
            }
        });
    } else {
        return;
    }
}
</script>
@endsection